site_name: App Services Integration iApp

pages:
- ['index.md','Home']
- ['design.md','Design Methodology & Goals']
- ['datamodel.md','Data Model']
- ['logdebug.md','Logging & Debugging']
- ['execflow.md','Execution Flow']
- ['policies.md','Policy Bundling & Deployment']
- ['presoref.md','Presentation Layer Reference']

theme: readthedocs

repo_url: https://github.com/0xHiteshPatel/appsvcs_integration_iapp/
