site_name: App Services Integration iApp
pages:
- "Home": index.md
- "Design Methodology & Goals": design.md
- "Data Model": datamodel.md
- "Logging & Debugging": logdebug.md
- "Execution Flow": execflow.md
- "Policy Bundling & Deployment": policies.md
- "Presentation Layer Reference": presoref.md
theme: readthedocs
repo_url: https://github.com/0xHiteshPatel/appsvcs_integration_iapp/
